language: python
python:
  - "3.4"
# command to install dependencies
sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get update -qq
  - wget http://www.riverbankcomputing.com/static/Downloads/sip4/sip-4.13.3.tar.gz
  - tar zxvf sip-4.13.3.tar.gz
  - cd sip-4.13.3/
  - python configure.py
  - make
  - sudo make install
  - cd ..
  - python -c 'import sip'

install:
  - sudo apt-get -y install qt55[QTPACKAGE]

script:
  - source /opt/qt55/bin/qt55-env.sh
  - /opt/qt55/bin/qmake
  - make
  - curl -sL https://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.6/PyQt5_gpl-5.6.tar.gz -o PyQt5_gpl-5.6.tar.gz
  - tar xf PyQt5_gpl-5.6.tar.gz
  - cd PyQt5_gpl-5.6
  - python configure.py --confirm-license
  - make -j 2
  - sudo make install
  - python PoloTrader.pyw
branches:
  only:
    - master