language: python
python:
  - "3.4"
# command to install dependencies
sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt55[QTPACKAGE]

script:
  - source /opt/qt55/bin/qt55-env.sh
  - /opt/qt55/bin/qmake
  - make
  - tar xvf PyQt5_gpl-5.6.tar.gz
  - cd PyQt5_gpl-5.6
  - python configure.py --confirm-license
  - make -j 2
  - sudo make install
  - python PoloTrader.pyw
branches:
  only:
    - master